summary: "Python Swagger"
description: "Swagger docs for a flask python rest api"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  description: "Accepts a input dictionary of inputs x1 and x2"
  required: true
  schema:
    type: "object"
    properties:
      x1:
        type: "integer"
        format: "int64"
        example : 45
      x2:
        type: "integer"
        format: "int64"
        example : 451
responses:
  405:
    description: "Invalid input"